<div class="x-column x-sm cs-ta-center x-1-1" style="padding: 0px;"><h2 class="h-custom-headline man"><span>
<p style="font-size:28px; color:#4091EB; font-weight:900;">TERMS OF USE</p>
</span></h2><hr class="x-hr mam" style="border-top-width: 2px;"><h4 class="h-custom-headline cs-ta-justify man" style="color: hsl(0, 0%, 0%);"><span>
<p style="text-align: center;"><strong></strong></p>
<p>
  
</p>
<p style="text-align: left;">Shareity is a social donation service (the “Service”) accessible via web browser at <a href="https://shareity.com" target="_blank" style="color: blue;" rel="noopener noreferrer"> shareity.me</a> (<a href="https://shareity.com" target="_blank" style="color: blue;" rel="noopener noreferrer">shareity.com</a>) (for information) or <a href="https://app.shareity.me" target="_blank" style="color: blue;" rel="noopener noreferrer">app.shareity.me</a> (<a href="https://my.shareity.com" target="_blank" style="color: blue;" rel="noopener noreferrer">my.shareity.com</a>) (to participate in a challenge) or <a href="https://members.shareity.me" target="_blank" style="color: blue;" rel="noopener noreferrer">members.shareity.me</a> (<a href="https://business.shareity.com" target="_blank" style="color: blue;" rel="noopener noreferrer">business.shareity.com</a>)(Dashboard to manage challenge and user data) (collectively the “Site”) operated by Shareity Inc. in the United States. Your access to and use of the Service constitutes acceptance by you or the entity you represent (“User” of “Users”) of the following terms and conditions of use (the “Terms of Use”).&nbsp;</p>
<p style="text-align: left;">There are a few definitions we’d like to get out of the way. A User is any individual who accesses the Site and uses the Service, regardless of whether it is on their own personal behalf or on the behalf of a Brand, Cause or Promoter. A User can be an individual challenge participant (“Participant”), an individual who contributes (“Sponsors”) a donation to a challenge campaign (“Cause”), the organizer of their own Cause or the (“Promoter”), marketing coordinator of campaigns. A Cause might more often be an organized not-for-profit, individual, charitable fund, governmental organization, or other entity but not necessarily so. Likewise, much of the time the Sponsor (“Brand”) of a challenge campaign will be a company, corporation, individual, government organization or charitable fund that has agreed to Sponsor the donation based on each Participant’s completion of the challenge.&nbsp;</p>
<p style="text-align: left;">If you do not agree to these Terms of Use, you may not access or use the Service.&nbsp;</p>
<p style="text-align: left;">The Service and Site are protected by intellectual property laws worldwide. Nothing in these Terms of Use shall be deemed to confer any third-party rights or benefits on any such content.</p>
<p style="text-align: left;">The Service allows Participants to direct donations by Brands in support of selected Causes as displayed in the Service. You acknowledge that the Cause that may be listed in the Site has subscribed to the Services on their own, and that SHAREITY MAKES NO REPRESENTATION OR WARRANTY REGARDING ANY PURPOSE, ITS VALIDITY, TAX-EXEMPT STATUS, OR ACCURACY OF ANY INFORMATION ABOUT THE CAUSE. Only Causes that have subscribed and agreed to the Shareity Service may receive donations from a Participant’s use of the Service.</p>
<p style="text-align: justify;">
  
</p>
<p style="text-align: left;">A Participant does not have to contribute any funds themselves to participate in a challenge campaign, although they certainly may do so (becoming a “Sponsor”). We at Shareity have no role in or responsibility for the relationship between the Brand/Sponsor and the Cause nor do we guarantee fulfillment of the Brand/Sponsor/Promoter’s commitment to deliver the promised donations. Each Brand/Sponsor communicates directly with the Cause with respect to how and when the donation will be made, directly in our Shareity Dashboard. The Services provided under these Terms of Use are subject to payment of fees by the Brand to us (“Fees”). The amount of the Fees varies with each campaign, depending upon the members subscribed, actions, interactions, aggregate donation amount and the number of individual donations. The Fees that we charge a Brand are for management of the campaign and use of platform. <b>We do not charge the Cause any fees for Brand Sponsored Challenges and neither request nor permit any deduction from the donation.</b></p>
<p style="text-align: left;">Challenges are voluntary and elected.  Shareity is not endorsing the use of the platform and or challenges for any other purpose other than raising money. Further Shareity does not protect or defend the integrity of any particular challenge, its purpose or outcome.  Shareity does not recommend or take responsibility for any challenge ideas or their effects on society/users/causes/brands.  Challenges should always be done with caution and awareness of surroundings, with regard to personal and public safety, property and human rights.  Shareity is not liable for any damages or negative results from improper use of the platform by Users, Causes, Brands or Promoters, in connection with challenges or other promotional means.  Always use caution when planning, implementing or participating in a challenge. </p>
<p style="text-align: left;">By agreeing to these Terms of Use, each Brand commits to paying the Fees to Shareity directly via payment processor, credit card, bank transfer or certified check in the form of (“Credits”) at the beginning of every campaign. One Credit is required for every participant added to the database (participating in the challenge). Credits must be bought before a campaign can become active in the database and Site.  Credits must be for the full amount of the campaign for total anticipated Users.  For example: Brand wants to donate $10,000 at $1 per user – they must purchase 10,000 Credits (total number or participants in the challenge).  The price of credits may change based on demand and services provided. Credits can also be used to send out messages and rewards to users, buy Keywords, or start new campaigns.  If Credits are not fully used in the intended campaign (campaign has ended or not reach a certain goal), they can be used in future campaigns, promotions, or outreach as they never expire. </p>
<p style="text-align: left;">Participants may also receive benefits from a Brand, Cause, Promotor, or Shareity for completing a challenge (ie: rewards, messages, status ratings, SWAG). These rewards can be promotional material but cannot constitute SPAM.  Shareity, a Brand, Cause, or Promoter may also conduct contests and/or sweepstakes through the Site, abiding by local governing laws and regulations. </p>
<p style="text-align: left;">We expect that each participating Brand/Sponsor/Promoter will take every reasonable care to ensure that all donations and related transactions are conducted via a secure connection. However, the security of information and payments transmitted via the internet cannot be guaranteed. The Participant and Cause each acknowledges and agrees that: (i) donations are at a Brand’s own discretion; and (ii) we have no liability whatsoever for (a) any loss the Participant, Brand, or Cause may suffer if a Brand fails to fulfill its donation commitment or (b) if a third party obtains unauthorized access to any information provided by the User.  &nbsp;</p>
<p style="text-align: left;">By accepting these Terms of Use, each Brand/Sponsor commits and promises to deliver to the donation it has offered for each challenge campaign Cause. The donation commitment is described in each challenge campaign and set between the Brand and Cause during campaign Set Up. For example, a Brand may commit to deliver $1 for each Participant who completes a challenge or a Brand may commit to deliver a certain amount of goods or services to the Cause if a certain number of challenges are completed. The Brand must convey its donation in a reasonable time following completion or end of the challenge campaign. Shareity may block a Brand from participating in future challenge campaigns if we have reason to believe that a Brand has not fully delivered on its donation commitment. &nbsp;</p>
<p style="text-align: left;">Each Brand and Cause licenses to Shareity any trademarks, trade names, logos and any other content it uploads to the Site for the challenge campaign (“Campaign Content”). Each Brand and Cause represents and warrants that it has all requisite rights to upload such content and shall indemnify Shareity for any expenses or losses arising from a third party’s claim that Campaign Content infringes its intellectual property rights.  &nbsp;</p>
<p style="text-align: left;">Each Brand, Cause, or Promoter is responsible for using the Shareity Site and the Services in compliance with all applicable laws. Shareity is not responsible for identifying, assessing, or informing Users of which laws may apply in their use of the Site and the Service. Each Brand and Cause shall indemnify Shareity for any expenses or losses arising from use of the Service in violation of the laws of a particular jurisdiction. </p>
<p style="text-align: left;">Each Brand and Cause commits to participating in each challenge campaign for the duration of the campaign as specified in the campaign Set Up. </p>
<p style="text-align: left;">Our collection, retention and use of personal information through the Service is described in the <a href="http://shareity.com/pages/privacy-policy" target="_blank" style="color: blue;" rel="noopener noreferrer">Privacy Notice</a>. Causes and Brands that have access to User information collected during a challenge campaign must use personal information only as permitted in these Terms of Use and the Shareity Privacy Notice.</p>
<p style="text-align: left;">The Service integrates third-party services such as Facebook and contains links to third-party webpages. Third-party services and webpages are not under our control and are subject to the respective third-party’s terms and conditions. </p>
<p style="text-align: left;">The Service is provided “as is” and “as available”, without warranty of any kind, either express or implied, including, without limitation, warranties of merchantability, fitness for a particular purpose and non-infringement. We do not make any warranties or representations as to accuracy or completeness. We periodically change, improve or update the Service. </p>
<p style="text-align: left;">The mention or omission of specific Brands, Promoters, Causes, Companies, their products or brand names in the Service or Site does not imply any endorsement or judgment on the part of Shareity. </p>
<p style="text-align: left;">Shareity’s name and logo (the “Shareity Marks”) are the exclusive property of Shareity and are protected under US and international law. Unauthorized use of the Shareity Marks is prohibited. The Shareity Marks may not be reproduced or used in any manner without our prior written permission outside of the platform. </p>
<p style="text-align: left;">We reserve the exclusive right in our sole discretion to (i) alter, limit or discontinue the Service in any respect; (ii) deny User access to the Service without notice; and (iii) modify these general Terms of Use. </p>
<p style="text-align: left;">All Users agree to the following terms governing Shareity’s use of Cellular services:</p>
<p style="text-align: left;">1. When Users opt-in to the service, Shareity will send User an SMS message with a link to the Shareity website.</p>
<p style="text-align: left;">2. Users can cancel the SMS service at any time. Users can also text “STOP” to (I WILL FILL THAT) to irrevocably stop messages. After a User sends the SMS message “STOP” to Shareity, Shareity will send the User an SMS message to confirm that the User has been unsubscribed. After this, the User will no longer receive SMS messages from Shareity. If the User wants to join again, a User may sign up as the User did the first time and Shareity will start sending SMS messages to the User again.</p>
<p style="text-align: left;">3. If at any time a User forgets what keywords are supported, User may text “HELP” to (I WILL FILL THAT) . After a User sends the SMS message “HELP” to Shareity, Shareity will respond with instructions on how to use our service as well as how to unsubscribe.</p>
<p style="text-align: left;">4. Shareity is able to deliver messages to the following mobile phone carriers: Major carriers: AT&T, Verizon Wireless, Sprint, T-Mobile, MetroPCS, U.S. Cellular, Alltel, Boost Mobile, Nextel, and Virgin Mobile. Minor carriers: Alaska Communications Systems (ACS), Appalachian Wireless (EKN), Bluegrass Cellular, Cellular One of East Central IL (ECIT), Cellular One of Northeast Pennsylvania, Cincinnati Bell Wireless, Cricket, Coral Wireless (Mobi PCS), COX, Cross, Element Mobile (Flat Wireless), Epic Touch (Elkhart Telephone), GCI, Golden State, Hawkeye (Chat Mobility), Hawkeye (NW Missouri), Illinois Valley Cellular, Inland Cellular, iWireless (Iowa Wireless), Keystone Wireless (Immix Wireless/PC Man), Mosaic (Consolidated or CTC Telecom), Nex-Tech Wireless, NTelos, Panhandle Communications, Pioneer, Plateau (Texas RSA 3 Ltd), Revol, RINA, Simmetry (TMP Corporation), Thumb Cellular, Union Wireless, United Wireless, Viaero Wireless, and West Central (WCC or 5 Star Wireless). ***Carriers are not liable for delayed or undelivered messages***</p>
<p style="text-align: left;">5. As always, message and data rates may apply for any messages sent to a User from Shareity and to Shareity from Users. 1 message per request. If User has any questions about their text plan or data plan, it is best to contact their wireless provider. For all questions about the services provided by this short code, Users can send an email to steve@shareity.com.</p>
<p style="text-align: left;">6.If Users have any questions regarding privacy, please read our <a href="http://shareity.com/pages/privacy-policy" target="_blank" style="color: blue;" rel="noopener noreferrer">Privacy Notice</a></p>
<p style="text-align: justify;">
  
</p>
<p style="text-align: left;">USE OF THE SERVICES AND THE SITE IS AT YOUR SOLE RISK. INFORMATION TRANSMITTED THROUGH THE INTERNET IS NEVER COMPLETELY SECURE. NEITHER SHAREITY, NOR ANY OF SHAREITY’S OWNERS, EMPLOYEES, AFFILIATES, AGENTS, REPRESENTATIVES, OR LICENSORS (COLLECTIVELY, “SHAREITY ASSOCIATES”) SHALL BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY COMPENSATORY, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, OR ATTORNEYS’ FEES, OR FOR LOST DATA OR LOST PROFIT, ARISING OUT OF YOUR USE OF THE SERVICES OR SITE OR INABILITY TO GAIN ACCESS TO OR USE THE SERVICES OR SITE OR OUT OF ANY BREACH OF ANY WARRANTY, EVEN IF SHAREITY OR A SHAREITY ASSOCIATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR SUCH DAMAGES WERE FORESEEABLE. </p>
<p style="text-align: left;">YOUR SOLE RIGHT AND REMEDY WITH RESPECT TO ANY DISPUTE WITH SHAREITY IS TO STOP USING THE SERVICES. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL, INCIDENTAL OR SPECIAL DAMAGES, IN SUCH STATES AND JURISDICTIONS LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW. IF THE FOREGOING LIMITATIONS ARE UNENFORCEABLE, SHAREITY’S LIABILITY TO YOU UNDER THESE TERMS SHALL NOT EXCEED ONE US DOLLAR. </p>
<p style="text-align: left;">THE SITE IS CONTROLLED, OPERATED AND ADMINISTERED BY SHAREITY FROM ITS OFFICES WITHIN THE UNITED STATES. SHAREITY MAKES NO WARRANTY OR REPRESENTATION THAT MATERIAL AVAILABLE THROUGH THE SITE IS LEGAL, APPROPRIATE, OR AVAILABLE FOR USE OUTSIDE THE UNITED STATES.</p>
<p style="text-align: left;">The following is a partial list of prohibited activities on or through the Service and Site: (1) using a robot, spider, script, automated process, or manual process to “scrape” the Site’s listings or content; (2) taking any action that imposes an unreasonable or disproportionately large load on Shareity’s hardware or software infrastructure; (3) sending SPAM to Shareity users or others; (4) attempting to reverse engineer, decompile, disassemble or otherwise obtain the source code to the Site; (5) engaging in or promoting any illegal activities; (6) engaging in any activity that markets another business or attracts Shareity users to a third party; (7) submitting content that is offensive, obscene, harmful to minors, illegal, abusive, threatening, defamatory, or misleading; or (8) using the services if you are or wish to assist a person or entity who is on a Specially Designated National List of the U.S. Department of the Treasury Office of Foreign Asset Control (“OFAC”) or otherwise prohibited from accessing the U.S. financial system. </p>
<p style="text-align: left;">Shareity respects the intellectual property rights of others and desires to offer a platform that contains no content that violates those rights. These Terms of Use require that information posted by Users be accurate, lawful and not in violation of the rights of third parties. To promote these objectives, we provide a process for submission of complaints concerning content posted by our Users. </p>
<p style="text-align: justify;">Please note that whether or not we disable access to or remove content, we may make a good faith attempt to forward the written notification, including the complainant’s contact information, to the User who posted the content and/or take other reasonable steps to notify the User that Shareity has received notice of an alleged violation of intellectual property rights or other content violation. It is also our policy, in appropriate circumstances and in our discretion, to disable and/or terminate the accounts of Users who infringe or repeatedly infringe the rights of others or otherwise post unlawful content. </p>
<p style="text-align: left;">Any notice or counter-notice you submit must be truthful and must be submitted under penalty of perjury. A false notice or counter-notice may give rise to personal liability. You may therefore want to seek the advice of legal counsel before submitting a notice or a counter-notice.</p>
<p style="text-align: left;">Pursuant to the Digital Millennium Copyright Act (17 U.S.C. § 512), Shareity has implemented procedures for receiving written notification of claimed infringements. Shareity has also designated an agent to receive notices of claimed copyright infringement. If you believe in good faith that your copyright has been infringed, you may complete and submit a Notice of Copyright Infringement form or otherwise provide a written communication which contains: </p>
<p style="text-align: left;">1. An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; </p>
<p style="text-align: left;">2. A description of the copyrighted work that you claim has been infringed;</p>
<p style="text-align: left;">3. A description specifying the location on our website of the material that you claim is infringing; </p>
<p style="text-align: left;">4. Your email address and your mailing address and/or telephone number; </p>
<p style="text-align: left;">5. A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and </p>
<p style="text-align: left;">6. A statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf. </p>
<p style="text-align: justify;">Please submit your notice to our Copyright Agent as follows: </p>
<p style="text-align: justify;">steve@shareity.com</p>
<p style="text-align: justify;">
  
</p>
<p style="text-align: left;">We reserve the right to seek all remedies available by law for any violation of these Terms of Use including any rights of Shareity in the Service and the Site. No waiver by Shareity of any provision of these Terms of Use shall be binding except as set forth in writing and signed by its duly authorized representative. Blocking a User from using the Service or the Site shall not limit Shareity’s other legal or equitable remedies for violation of these Terms of Use. </p>
<p style="text-align: left;">These Terms of Use and any dispute arising therefrom shall be exclusively governed by the laws of the Commonwealth of Massachusetts, excluding its choice of law provisions. These Terms of Use and any Order Form completed between Shareity and each Brand, Cause or Promoter represents the entire agreement between Shareity and each User relating to the Services and the Site. These Terms of Use alone fully and completely expresses the agreement of the parties relating to the Services and the Site. There are no other courses of dealing, understanding, agreements, order forms, representations or warranties, written or oral, except as set forth herein. The integration of any Order Form within these Terms of Use is applicable only with respect to the parties executing such Order Form. Other persons, such as Participants, have no such Order Form incorporated within these Terms of Use, and any User is not considered a third party beneficiary of any Order Form. </p>
<p style="text-align: left;">To the extent that there exists more than one language version of these Terms of Use and there is any inconsistency between the versions, the English version shall always prevail. </p>
<p style="text-align: left;">If you have any questions about this Terms of Use, please contact us via steve@shareity.com </p>
<p style="text-align: justify;">Last updated: December 10, 2019 </p>
<p>
  
</p>
</span></h4></div>